### ISSUE TITLE
Nested Navigation Fails After Multiple Nested Routes Opened

### ISSUE THREAD

**Issue by thomastthai** [g-30/flutter_nested_navigation#1] opened 2023-01-17 20:37 UTC
I am following the [Nested stateful navigation with ShellRoute #2650](https://github.com/flutter/packages/pull/2650) on Flutter and saw your [comment](https://github.com/flutter/packages/pull/2650#issuecomment-1384097077). Thanks for sharing. There is a bug in the code. The following steps will replicate the bug:

1. When your example app loads, it shows 'Page A'. Click on 'Go to details'. Leave that page open. 
2. Click on 'Page B' in the bottom navbar. 'Page B' will display. Click on 'Go to details'. Leave that page open.
3. In the bottom navbar, click 'Page A'.
4. At the top appbar, click on the back arrow ⬅. You should still be on 'Page A'.
5. Click on 'Go to details' under 'Page A' in the center again. It won't go anywhere.
6. Click on 'Page B' in the bottom navbar. 'Details /b/details' will display.
7. At the top appbar, click on the back arrow ⬅. The screen will change to 'Page B'. 
8. Click on 'Go to details' under 'Page B' in the center again. It won't go anywhere.

**Comment by fennel-ptorchia** [comment] 2023-01-18 18:01
We're experiencing this issue as well!

**Comment by g-30** [comment] 2023-01-18 19:09
Thank you for reporting this and the steps to reproduce. I'll take a look asap.

**Comment by g-30** [comment] 2023-01-21 13:08
@thomastthai I pulled the latest changes in the git repo this package depends upon; the issue seems to be fixed now on my end. Please try running `flutter pub upgrade` and then build the example app on your machine and lmk if it works for you as well.

**Comment by g-30** [comment] 2023-01-21 13:09
`flutter pub upgrade` should display the following:

\* go_router 6.1.0 from git https://github.com/g-30/flutter_packages.git at **f9a260** in packages/go_router (was 6.1.0 from git https://github.com/g-30/flutter_packages.git at **5b668f** in packages/go_router)

**Comment by thomastthai** [comment] 2023-01-21 13:59
@g-30, thank you for the update. That bug is resolved.

**Closed as completed** 2023-01-21 13:59 UTC
